version: '3.8'

services:
  baileys-api:
    container_name: baileys-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
      - prisma:/prisma
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      URL_WEBHOOK: ${URL_WEBHOOK}
      ENABLE_WEBHOOK: ${ENABLE_WEBHOOK}
      ENABLE_WEBSOCKET: ${ENABLE_WEBSOCKET}
      BOT_NAME: ${BOT_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      RECONNECT_INTERVAL: ${RECONNECT_INTERVAL}
      MAX_RECONNECT_RETRIES: ${MAX_RECONNECT_RETRIES}
      SSE_MAX_QR_GENERATION: ${SSE_MAX_QR_GENERATION}
      SESSION_CONFIG_ID: ${SESSION_CONFIG_ID}
      API_KEY: ${API_KEY}

volumes:
  prisma:
